method: &method plasmode

data:
  real_data_icd9_path: &real_data_icd9_path /scratch/zhenkewu_root/zhenkewu1/chenxran/syntheticEHR/processed_mimic.matrix
  real_data_phecodexm_path: &real_data_phecodexm_path /scratch/zhenkewu_root/zhenkewu1/chenxran/syntheticEHR/data/mimic3-real-phecodexm.npy
  synthetic_data_path: &synthetic_data_path /home/chenxran/projects/synthEHRella
  synthetic_data_type: &synthetic_data_type icd9

generation:
  method: *method
  ckpt_dir: &ckpt_dir /home/chenxran/projects/synthEHRella
  params:
    num_gen_samples: 50000
    real_data_path: *real_data_icd9_path
    ckpt_dir: *ckpt_dir

evaluation:
  output_dir: /home/chenxran/projects/synthEHRella
  real_data_icd9_path: *real_data_icd9_path
  real_data_phecodexm_path: *real_data_phecodexm_path
  synthetic_data_path: *synthetic_data_path
  fidelity: True
  utility: True
  privacy: True
